
import { Translations, AppState } from './types';

// TODO: Replace this with your actual Google Client ID from Google Cloud Console
// Example: "123456789-abcdefgh.apps.googleusercontent.com"
export const GOOGLE_CLIENT_ID: string = ""; 

export const INITIAL_STATE: AppState = {
  user: null,
  strategies: [],
  currentStrategyId: null,
  currentMonthId: null,
  settings: {
    theme: 'dark',
    language: 'en',
    isOnboardingComplete: false,
  },
};

export const TRANSLATIONS: Record<'en' | 'fa', Translations & any> = {
  en: {
    welcomeTitle: "Welcome to FxAnalytics",
    welcomeSubtitle: "Track, Analyze, and Master your Strategies with professional precision.",
    getStarted: "Get Started",
    strategies: "Strategies",
    addStrategy: "New Strategy",
    newStrategyName: "Strategy Name",
    months: "Months",
    addMonth: "New Month",
    newMonthName: "Month Name (e.g. Jan 2024)",
    back: "Back",
    winRate: "Win Rate",
    netProfit: "Net Profit",
    totalGain: "Total Gain",
    totalLoss: "Total Loss",
    totalTrades: "Total Trades",
    equityCurve: "Equity Curve",
    tradeLog: "Trade Journal",
    date: "Date",
    day: "Day",
    pair: "Pair",
    dir: "Dir",
    rr: "R:R",
    result: "Result",
    pnl: "PnL %",
    pips: "Pips",
    maxExcursion: "Max %",
    actions: "",
    addTrade: "Add Trade",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    notes: "Notes",
    notesPlaceholder: "Write your analysis, rules, or thoughts here...",
    aiAnalysis: "AI Analyst",
    askAi: "Analyze Performance",
    analyzing: "Thinking...",
    viewAnalysis: "View Analysis",
    close: "Close",
    signOut: "Sign Out",
    profile: "Profile",
    theme: "Theme",
    language: "Language",
    confirmDeleteTitle: "Are you sure?",
    confirmDeleteStrategyMsg: "This will permanently delete this strategy and all contained months and trades. This action cannot be undone.",
    confirmDeleteMonthMsg: "This will permanently delete this month and all recorded trades. This action cannot be undone.",
    confirmDeleteAction: "Yes, Delete",
    chooseAccount: "Choose an account",
    useAnotherAccount: "Use another account",
    stayLoggedIn: "Stay logged in",
    settings: "Settings",
    account: "Account",
    security: "Security",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    update: "Update",
    passwordUpdated: "Password updated successfully",
    incorrectPassword: "Incorrect current password",
    usernameUpdated: "Username updated successfully",
  },
  fa: {
    welcomeTitle: "به FxAnalytics خوش آمدید",
    welcomeSubtitle: "استراتژی‌های خود را با دقت حرفه‌ای ردیابی، تحلیل و مسلط شوید.",
    getStarted: "شروع کنید",
    strategies: "استراتژی‌ها",
    addStrategy: "استراتژی جدید",
    newStrategyName: "نام استراتژی",
    months: "ماه‌ها",
    addMonth: "ماه جدید",
    newMonthName: "نام ماه (مثلا دی ۱۴۰۲)",
    back: "بازگشت",
    winRate: "نرخ برد",
    netProfit: "سود خالص",
    totalGain: "کل سود",
    totalLoss: "کل ضرر",
    totalTrades: "تعداد معاملات",
    equityCurve: "منحنی رشد",
    tradeLog: "دفترچه معاملات",
    date: "تاریخ",
    day: "روز",
    pair: "ارز",
    dir: "جهت",
    rr: "ریسک:ریوارد",
    result: "نتیجه",
    pnl: "سود/ضرر ٪",
    pips: "پیپ",
    maxExcursion: "حداکثر ٪",
    actions: "",
    addTrade: "افزودن معامله",
    delete: "حذف",
    cancel: "لغو",
    save: "ذخیره",
    notes: "یادداشت‌ها",
    notesPlaceholder: "تحلیل‌ها، قوانین یا افکار خود را اینجا بنویسید...",
    aiAnalysis: "تحلیلگر هوشمند",
    askAi: "تحلیل عملکرد",
    analyzing: "در حال تفکر...",
    viewAnalysis: "مشاهده تحلیل",
    close: "بستن",
    signOut: "خروج",
    profile: "پروفایل",
    theme: "تم",
    language: "زبان",
    confirmDeleteTitle: "آیا مطمئن هستید؟",
    confirmDeleteStrategyMsg: "این عمل استراتژی و تمام ماه‌ها و معاملات آن را برای همیشه حذف می‌کند. این عملیات غیرقابل بازگشت است.",
    confirmDeleteMonthMsg: "این عمل ماه و تمام معاملات ثبت شده در آن را حذف می‌کند. این عملیات غیرقابل بازگشت است.",
    confirmDeleteAction: "بله، حذف کن",
    chooseAccount: "انتخاب حساب کاربری",
    useAnotherAccount: "استفاده از حساب دیگر",
    stayLoggedIn: "مرا به خاطر بسپار",
    settings: "تنظیمات",
    account: "حساب کاربری",
    security: "امنیت",
    changePassword: "تغییر رمز عبور",
    currentPassword: "رمز عبور فعلی",
    newPassword: "رمز عبور جدید",
    update: "بروزرسانی",
    passwordUpdated: "رمز عبور با موفقیت تغییر کرد",
    incorrectPassword: "رمز عبور فعلی اشتباه است",
    usernameUpdated: "نام کاربری با موفقیت تغییر کرد",
  },
};
