
import { Translations, AppState } from './types';

export const INITIAL_STATE: AppState = {
  user: null,
  strategies: [],
  currentStrategyId: null,
  currentMonthId: null,
  settings: {
    theme: 'dark',
    language: 'en',
    isOnboardingComplete: false,
  },
};

export const TRANSLATIONS: Record<'en' | 'fa', Translations> = {
  en: {
    welcomeTitle: "Welcome to TradeMaster",
    welcomeSubtitle: "Track, Analyze, and Master your Strategies with professional precision.",
    getStarted: "Get Started",
    strategies: "Strategies",
    addStrategy: "New Strategy",
    newStrategyName: "Strategy Name",
    months: "Months",
    addMonth: "New Month",
    newMonthName: "Month Name (e.g. Jan 2024)",
    back: "Back",
    winRate: "Win Rate",
    netProfit: "Net Profit",
    totalGain: "Total Gain",
    totalLoss: "Total Loss",
    totalTrades: "Total Trades",
    equityCurve: "Equity Curve",
    tradeLog: "Trade Journal",
    date: "Date",
    day: "Day",
    pair: "Pair",
    dir: "Dir",
    rr: "R:R",
    result: "Result",
    pnl: "PnL %",
    pips: "Pips",
    maxExcursion: "Max %",
    actions: "",
    addTrade: "Add Trade",
    delete: "Delete",
    cancel: "Cancel",
    save: "Save",
    notes: "Notes",
    notesPlaceholder: "Write your analysis, rules, or thoughts here...",
    aiAnalysis: "AI Analyst",
    askAi: "Analyze Performance",
    analyzing: "Thinking...",
    viewAnalysis: "View Analysis",
    close: "Close",
    signInGoogle: "Sign in with Google",
    signOut: "Sign Out",
    profile: "Profile",
    theme: "Theme",
    language: "Language"
  },
  fa: {
    welcomeTitle: "به ترید مستر خوش آمدید",
    welcomeSubtitle: "استراتژی‌های خود را با دقت حرفه‌ای ردیابی، تحلیل و مسلط شوید.",
    getStarted: "شروع کنید",
    strategies: "استراتژی‌ها",
    addStrategy: "استراتژی جدید",
    newStrategyName: "نام استراتژی",
    months: "ماه‌ها",
    addMonth: "ماه جدید",
    newMonthName: "نام ماه (مثلا دی ۱۴۰۲)",
    back: "بازگشت",
    winRate: "نرخ برد",
    netProfit: "سود خالص",
    totalGain: "کل سود",
    totalLoss: "کل ضرر",
    totalTrades: "تعداد معاملات",
    equityCurve: "منحنی رشد",
    tradeLog: "دفترچه معاملات",
    date: "تاریخ",
    day: "روز",
    pair: "ارز",
    dir: "جهت",
    rr: "ریسک:ریوارد",
    result: "نتیجه",
    pnl: "سود/ضرر ٪",
    pips: "پیپ",
    maxExcursion: "حداکثر ٪",
    actions: "",
    addTrade: "افزودن معامله",
    delete: "حذف",
    cancel: "لغو",
    save: "ذخیره",
    notes: "یادداشت‌ها",
    notesPlaceholder: "تحلیل‌ها، قوانین یا افکار خود را اینجا بنویسید...",
    aiAnalysis: "تحلیلگر هوشمند",
    askAi: "تحلیل عملکرد",
    analyzing: "در حال تفکر...",
    viewAnalysis: "مشاهده تحلیل",
    close: "بستن",
    signInGoogle: "ورود با گوگل",
    signOut: "خروج",
    profile: "پروفایل",
    theme: "تم",
    language: "زبان"
  },
};